name: CrystolEssentials
main: com.joaootavios.crystolnetwork.essentials.EssentialsPlugin
version: CrystolNetwork
authors: [JoaoOtavioS & WalkDev]
softdepend: [RCore, CrystolOffices, CrystolGuerra, CrystolEconomy, Factions]